services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joyas_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - joyas_network

  webserver:
    image: nginx:alpine
    container_name: joyas_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - joyas_network

  database:
    image: mysql:8.0
    container_name: joyas_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: joyas_db
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - joyas_network
      
  redis:
    image: redis:alpine
    container_name: joyas_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - joyas_network

volumes:
  db_data:
    driver: local

networks:
  joyas_network:
    driver: bridge